version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp
    ports:
      - "90:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  app_dist: