version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: myapp
    ports:
      - "90:80"
    volumes:
      - .:/app
      - /app/node_modules