version: "3.9"

services:
  app:
    build: .
    command: npm run build
    image: myapp:latest
    container_name: myapp
    ports:
      - "90:90"
    volumes:
      - .:/app
      - /app/node_modules
networks:
    app:
        driver: bridge